flysystem:
    storages:
        pimcore.dataImporter.upload.storage:
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/tmp/datahub/dataimporter/upload'
        pimcore.dataImporter.preview.storage:
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/tmp/datahub/dataimporter/preview'
