flysystem:
    storages:
        pimcore.dataImporter.upload.storage:
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/tmp/datahub/dataimporter/upload'
        pimcore.dataImporter.preview.storage:
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/tmp/datahub/dataimporter/preview'


framework:
    messenger:
        transports:
            pimcore_data_import:
                dsn: 'doctrine://default?queue_name=pimcore_data_import'

        routing:
            'Pimcore\Bundle\DataImporterBundle\Messenger\DataImporterMessage': pimcore_data_import

pimcore_data_hub:
    supported_types:
        dataImporterDataObject: "Pimcore\\Bundle\\DataImporterBundle"