_data_hub_data_importer_data_object_admin:
    resource: "@PimcoreDataImporterBundle/Controller/ConfigDataObjectController.php"
    type:     attribute
    options:
        expose: true

_data_hub_data_importer_connections:
    resource: "@PimcoreDataImporterBundle/Controller/ConnectionController.php"
    type:     attribute
    options:
        expose: true

_data_hub_data_importer_data_object_push:
    resource: "@PimcoreDataImporterBundle/Controller/PushImportController.php"
    type:     attribute

_data_hub_data_importer_mcp:
    resource: "@PimcoreDataImporterBundle/Mcp/Controller"
    type:     attribute

pimcore_data_importer_studio:
    resource: .
    type: pimcore_data_importer_studio

