_data_hub_data_importer_data_object_push:
    resource: "@PimcoreDataImporterBundle/Controller/PushImportController.php"
    type:     attribute

_data_hub_data_importer_mcp:
    resource: "@PimcoreDataImporterBundle/Mcp/Controller"
    type:     attribute

pimcore_data_importer_studio:
    resource: "@PimcoreDataImporterBundle/Controller/Studio"
    type: attribute
    prefix: '%pimcore_studio_backend.url_prefix%/bundle/data-importer'
    options:
        expose: true


